[package]
name = "maki-monitor"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dev-dependencies]
maki-agent = { git = "https://github.com/lu-zero/maki", rev = "5e41f300eeaae4f20588cc84180c3b1a64aa26cd" }
maki-lua = { git = "https://github.com/lu-zero/maki", rev = "5e41f300eeaae4f20588cc84180c3b1a64aa26cd" }
maki-storage = { git = "https://github.com/lu-zero/maki", rev = "5e41f300eeaae4f20588cc84180c3b1a64aa26cd" }
serde_json = "1"
smol = "2"
