[package]
name = "maki-monitor"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dev-dependencies]
maki-agent = { git = "https://github.com/tontinton/maki", rev = "b14689365061d7b1c5fb0e6026e32f7cbe7d2a6f" }
maki-lua = { git = "https://github.com/tontinton/maki", rev = "b14689365061d7b1c5fb0e6026e32f7cbe7d2a6f" }
maki-storage = { git = "https://github.com/tontinton/maki", rev = "b14689365061d7b1c5fb0e6026e32f7cbe7d2a6f" }
serde_json = "1"
smol = "2"
